<?php

require_once(dirname(__FILE__).'/ColissimoClient.php');
require_once(dirname(__FILE__).'/Request/AbstractColissimoRequest.php');
require_once(dirname(__FILE__).'/Request/ColissimoGenerateLabelRequest.php');
require_once(dirname(__FILE__).'/Request/ColissimoGenerateBordereauRequest.php');
require_once(dirname(__FILE__).'/Request/ColissimoWidgetAuthenticationRequest.php');
require_once(dirname(__FILE__).'/Request/ColissimoMailboxDetailsRequest.php');
require_once(dirname(__FILE__).'/Request/ColissimoTrackingEnrichiRequest.php');
require_once(dirname(__FILE__).'/Request/ColissimoTrackingSimpleRequest.php');
require_once(dirname(__FILE__).'/Request/ColissimoCheckGenerateLabelRequest.php');
require_once(dirname(__FILE__).'/Request/ColissimoPlanPickupRequest.php');
require_once(dirname(__FILE__).'/Request/ColissimoTrackingTimelineRequest.php');
require_once(dirname(__FILE__).'/Response/ColissimoReturnedResponseInterface.php');
require_once(dirname(__FILE__).'/Response/AbstractColissimoResponse.php');
require_once(dirname(__FILE__).'/Response/ColissimoResponseParser.php');
require_once(dirname(__FILE__).'/Response/ColissimoGenerateLabelResponse.php');
require_once(dirname(__FILE__).'/Response/ColissimoGenerateBordereauResponse.php');
require_once(dirname(__FILE__).'/Response/ColissimoWidgetAuthenticationResponse.php');
require_once(dirname(__FILE__).'/Response/ColissimoMailboxDetailsResponse.php');
require_once(dirname(__FILE__).'/Response/ColissimoTrackingEnrichiResponse.php');
require_once(dirname(__FILE__).'/Response/ColissimoTrackingSimpleResponse.php');
require_once(dirname(__FILE__).'/Response/ColissimoCheckGenerateLabelResponse.php');
require_once(dirname(__FILE__).'/Response/ColissimoPlanPickupResponse.php');
require_once(dirname(__FILE__).'/Response/ColissimoTrackingTimelineResponse.php');
